# Generated by Django 2.2 on 2020-07-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='profile',
        ),
    ]
